# Generated by Django 3.0.8 on 2020-07-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200717_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_ask',
            new_name='ask_question',
        ),
    ]
