# Generated by Django 3.0.8 on 2020-07-19 22:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200718_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
